config/routes.rb
Rails.application.routes.draw do

	resources(:puppies)
  

  root 'puppies#index'

#  Prefix Verb   URI Pattern                 Controller#Action
#    puppies GET    /puppies(.:format)          puppies#index
#            POST   /puppies(.:format)          puppies#create
#  new_puppy GET    /puppies/new(.:format)      puppies#new
# edit_puppy GET    /puppies/:id/edit(.:format) puppies#edit
#      puppy GET    /puppies/:id(.:format)      puppies#show
#            PATCH  /puppies/:id(.:format)      puppies#update
#            PUT    /puppies/:id(.:format)      puppies#update
#            DELETE /puppies/:id(.:format)      puppies#destroy
#       root GET    /                           puppies#index

end

app/models/puppy.rb
class Puppy < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  
  def index
  	@puppies = Puppy.all
  end

  def show
  	@puppy = Puppy.find_by_id params[:id]
  end

  def new
  	@puppy = Puppy.new
  end

  def create
  	@puppy = Puppy.new puppy_params
  	if @puppy.save 
  		redirect_to puppies_path
  	else 
  		render :new
  	end 
  end

  def update
  	@puppy = Puppy.find_by_id params[:id]
  	@puppy.update puppy_params
  		if @puppy.save 
  			redirect_to puppy_path(@puppy)
  		else 
  			render :edit
  		end 
  end 

  def edit
  	@puppy = Puppy.find_by_id(params[:id])
  	render :edit
  end

  def destroy
  	@puppy = Puppy.find_by_id(params[:id])
  	@puppy.destroy
  	redirect_to puppies_path
  end 

private 

  def puppy_params
  	params.require(:puppy).permit(:name, :image, :breed, :bio, :age)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PuppyRescue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/puppies/_form.html.erb
<% @puppies.each do |puppy| %>

    <%= link_to "Delete", puppy_path(puppy), method: :delete %>
    <%= link_to "Edit", edit_puppy_path(puppy)%>
    <p>
        <img src="<%= puppy.image %>">
    </p>

    <p>
        "<%= puppy.name %>"
    </p>
    
    <p>
        "<%= puppy.breed %>"
    </p>

    <p>
        "<%= puppy.bio %>"
    </p>

    <p>
        <a href="/puppies/"></a>
    </p>




<% end %>

app/views/puppies/_formEdit.html.erb
<%= form_for @puppy do |f|%>
  <div>
    <%= f.label :name%>
    <%= f.text_field :name, autofocus: true%>
  </div>
  <div>
    <%= f.label :image%>
    <%= f.text_field :image%>
  </div>
  <div>
    <%= f.label :breed%>
    <%= f.text_field :breed%>
  </div>
  <div>
    <%= f.label :bio%>
    <%= f.text_field :bio%>
  </div>
  <div>
    <%= f.label :age%>
    <%= f.text_field :age%>
  </div>
  <div>
    <%= f.submit%>
  </div>
<% end %>

app/views/puppies/edit.html.erb
<h1>Edit Puppy</h1>



<%= render "formEdit" %>

app/views/puppies/index.html.erb
<h1>Puppies</h1>
<h3><%= link_to "Add Puppy", new_puppy_path %></h3>

<%= render "form" %>

app/views/puppies/new.html.erb
<h1>New Puppy</h1>
<%= render "formEdit" %>

app/views/puppies/show.html.erb
<h1>Show Puppy</h1>

    <p>
        <img src="<%= @puppy.image %>">
    </p>

    <p>
        Name: <%= @puppy.name %>
    </p>
    
    <p>
        Bio: <%= @puppy.bio%>
    </p>

    <p>
        Age: <%= @puppy.age%>
    </p>

    <p>
        Breed: <%= @puppy.breed%>
    </p>

<%= link_to "Delete Puppy", @puppy, method: :delete%>